version: '3.4'
services:
  db-satuklinik:
    container_name: postgres-satuklinik
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB_NAME}
    healthcheck:
      test: 'pg_isready -U "$$PG_USER" -d "$$PG_DB_NAME"'
      interval: 10s
      timeout: 2s
      retries: 10
    volumes:
      - ${DATABASE_VOLUME}:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      local:
  
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - local
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}

networks:
  local:
    driver: bridge
