import { z as a } from "zod";
import {
  Lezzform as F,
  FormField as t,
  FormItem as m,
  FormLabel as l,
  FormControl as s,
  FormMessage as i,
  Input as b,
  Dropdown as p,
  DatePicker as L,
  PhoneNumberInput as S,
  TextArea as A,
  TwoColumn as k,
  Button as g,
} from "@lezzform/react";
import {
  CreditCard as C,
  User as B,
  Calendar as N,
  Phone as P,
} from "lucide-react";
import * as c from "react";
import { jsx as e, jsxs as n } from "react/jsx-runtime";
var I = a.object({
    medicalNumber: a.string().optional(),
    nik: a.string(),
    fullname: a.string(),
    sex: a.string(),
    blood: a.string(),
    birthAt: a.date(),
    phone: a
      .string()
      .max(14)
      .min(10)
      .refine(
        (u) =>
          !u ||
          /^([+]?[\s0-9]+)?(\d{3}|[(]?[0-9]+[)])?([-]?[\s]?[0-9])+$/.test(u),
        { message: "Invalid phone number format" }
      ),
    address: a.string(),
  }),
  z = "ihnd4xTL9pD7iGv2FJQv",
  K = ({
    onSubmit: u,
    onError: h,
    onSuccess: R,
    defaultValues: v,
    onAction: f,
    formProps: q,
  }) => {
    let d = c.useRef();
    c.useEffect(() => {
      u && (d.current = u);
    }, [u]);
    let y = c.useCallback(async (r, o) => {
      if (d.current) return d.current(r, o);
    }, []);
    return e(
      F,
      {
        id: z,
        defaultValues: v,
        onSubmit: y,
        onError: h,
        onSuccess: R,
        zodSchema: I,
        mode: "onSubmit",
        children: (r) =>
          n(F.Container, {
            children: [
              e(t, {
                control: r.control,
                name: "medicalNumber",
                disabled: !0,
                render: ({ field: o }) =>
                  n(m, {
                    children: [
                      e(l, { children: "Nomor Rekam Medis" }),
                      e(s, {
                        children: e(b, {
                          label: "Nomor Rekam Medis",
                          name: o.name,
                          value: o.value ?? "",
                          onBlur: o.onBlur,
                          onChange: o.onChange,
                          placeholder: "Generated By System",
                          disabled: o.disabled,
                          styles: { root: {} },
                          prefixAdornment: {
                            icon: e(C, { size: 18, color: "#000000" }),
                          },
                        }),
                      }),
                      e(i, {}),
                    ],
                  }),
              }),
              e(t, {
                control: r.control,
                name: "nik",
                render: ({ field: o }) =>
                  n(m, {
                    children: [
                      e(l, { isRequired: !0, children: "NIK" }),
                      e(s, {
                        children: e(b, {
                          label: "NIK",
                          name: o.name,
                          value: o.value ?? "",
                          onBlur: o.onBlur,
                          onChange: o.onChange,
                          placeholder: "NIK",
                          disabled: o.disabled,
                          isRequired: !0,
                          styles: { root: {} },
                          prefixAdornment: {
                            icon: e(C, { size: 18, color: "#000000" }),
                          },
                        }),
                      }),
                      e(i, {}),
                    ],
                  }),
              }),
              e(t, {
                control: r.control,
                name: "fullname",
                render: ({ field: o }) =>
                  n(m, {
                    children: [
                      e(l, { isRequired: !0, children: "Nama" }),
                      e(s, {
                        children: e(b, {
                          label: "Nama",
                          name: o.name,
                          value: o.value ?? "",
                          onBlur: o.onBlur,
                          onChange: o.onChange,
                          placeholder: "Nama",
                          disabled: o.disabled,
                          isRequired: !0,
                          styles: { root: {} },
                          prefixAdornment: {
                            icon: e(B, { size: 18, color: "#000000" }),
                          },
                        }),
                      }),
                      e(i, {}),
                    ],
                  }),
              }),
              e(t, {
                control: r.control,
                name: "sex",
                render: ({ field: o }) =>
                  n(m, {
                    children: [
                      e(l, { isRequired: !0, children: "Jenis Kelamin" }),
                      e(s, {
                        children: e(p.List, {
                          label: "Jenis Kelamin",
                          name: o.name,
                          value: o.value,
                          onChange: o.onChange,
                          items: [
                            { label: "Laki-laki", value: "male" },
                            { label: "Perempuan", value: "female" },
                          ],
                          isRequired: !0,
                          disabled: o.disabled,
                          styles: { root: {} },
                        }),
                      }),
                      e(i, {}),
                    ],
                  }),
              }),
              e(t, {
                control: r.control,
                name: "blood",
                render: ({ field: o }) =>
                  n(m, {
                    children: [
                      e(l, { isRequired: !0, children: "Golongan Darah" }),
                      e(s, {
                        children: e(p.List, {
                          label: "Golongan Darah",
                          name: o.name,
                          value: o.value,
                          onChange: o.onChange,
                          items: [
                            { label: "empty", value: "N/A" },
                            { label: "A", value: "a" },
                            { label: "B", value: "b" },
                            { label: "AB", value: "ab" },
                            { label: "O", value: "o" },
                          ],
                          isRequired: !0,
                          disabled: o.disabled,
                          styles: { root: {} },
                        }),
                      }),
                      e(i, {}),
                    ],
                  }),
              }),
              e(t, {
                control: r.control,
                name: "birthAt",
                render: ({ field: o }) =>
                  n(m, {
                    children: [
                      e(l, { isRequired: !0, children: "Tanggal Lahir" }),
                      e(s, {
                        children: e(L, {
                          label: "Tanggal Lahir",
                          name: o.name,
                          value: o.value,
                          onChange: o.onChange,
                          placeholder: "dd/mm/yyyy",
                          format: "PPP",
                          isRequired: !0,
                          styles: { root: {} },
                          disabled: o.disabled,
                          prefixAdornment: {
                            icon: e(N, { size: 18, color: "#000000" }),
                          },
                        }),
                      }),
                      e(i, {}),
                    ],
                  }),
              }),
              e(t, {
                control: r.control,
                name: "phone",
                render: ({ field: o }) =>
                  n(m, {
                    children: [
                      e(l, { isRequired: !0, children: "Nomor Telepon" }),
                      e(s, {
                        children: e(S, {
                          label: "Nomor Telepon",
                          name: o.name,
                          value: o.value ?? "",
                          onBlur: o.onBlur,
                          onChange: o.onChange,
                          disabled: o.disabled,
                          placeholder: "Nomor Telepon",
                          isRequired: !0,
                          styles: { root: {} },
                          prefixAdornment: {
                            icon: e(P, { size: 18, color: "#000000" }),
                          },
                        }),
                      }),
                      e(i, {}),
                    ],
                  }),
              }),
              e(t, {
                control: r.control,
                name: "address",
                render: ({ field: o }) =>
                  n(m, {
                    children: [
                      e(l, { isRequired: !0, children: "Alamat" }),
                      e(s, {
                        children: e(A, {
                          label: "Alamat",
                          name: o.name,
                          value: o.value ?? "",
                          onBlur: o.onBlur,
                          onChange: o.onChange,
                          disabled: o.disabled,
                          placeholder: "Alamat",
                          isRequired: !0,
                          styles: { root: {} },
                        }),
                      }),
                      e(i, {}),
                    ],
                  }),
              }),
              n(k, {
                styles: { root: {} },
                children: [
                  e(g, {
                    type: "reset",
                    className: "w-full",
                    styles: { root: { backgroundColor: "rgb(239, 68, 68)" } },
                    children: "Batalkan",
                  }),
                  e(g, {
                    type: "submit",
                    className: "w-full",
                    disabled: r.formState.isSubmitting,
                    isLoading: r.formState.isSubmitting,
                    styles: { root: { backgroundColor: "#2E584F" } },
                    children: "Daftar",
                  }),
                ],
              }),
            ],
          }),
      },
      z
    );
  };
export { K as Form };
